MAP = 'map'
NARRATOR = 'narrator'
PLAYERS = 'players'
DEATH = 'death'
DEADS = 'deads'

TIME = 'time'
STARTER = 'starter'
MORNING = 'morning'
AFTERNOON = 'afternoon'
NIGHT = 'night'
DAY = 'day'

PANIC = 'panic'
TRAPPED = 'trapped'
SLEEPING = 'sleeping'
FLEEING = 'fleeing'
AMBUSH = 'ambush'
THIRSTY = 'thirsty'
HUNGRY = 'hungry'
SLEEPY = 'sleepy'

ARM_WOUND = 'arm wound'
LEG_WOUND = 'leg wound'
BELLY_WOUND = 'belly wound'
HEAD_WOUND = 'head wound'
BLEEDING = 'bleeding'

AXE = 'axe'
SWORD = 'sword'
KNIFE = 'knife'
TRIDENT = 'trident'
SPEAR = 'spear'
CLUB = 'club'
HATCHET = 'hatchet'
MACE = 'mace'
