MAP = 'map'
NARRATOR = 'narrator'
PLAYERS = 'players'
DEATH = 'death'
DEADS = 'deads'

TIME = 'time'
STARTER = 'starter'
MORNING = 'morning'
AFTERNOON = 'afternoon'
NIGHT = 'night'
DAY = 'day'

PANIC = 'panic'
TRAPPED = 'trapped'
SLEEPING = 'sleeping'
